# fly.toml app configuration file generated for lab3 on 2025-03-07T15:33:29+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'chatbot-hcz'
primary_region = 'hkg'
console_command = '/code/manage.py shell'

[build]
  builder = 'paketobuildpacks/builder:base'

[env]
  PORT = '8080'

[[services]]
  internal_port = 8000
  protocol = 'tcp'
  
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = 'connections'

  [[services.ports]]
    port = 80
    handlers = ['http']

  [[services.ports]]
    handlers = ['tls', 'http']
    port = 443

[[vm]]
  size = 'shared-cpu-1x'
